# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 820ad0ed35be74ff6a711bb80c613ead729d0f953a2d7a6402f4eab8a98360e98f1b0ee038297fe74b6f53c515e87664fb1f6193c5d4f77e0d9ea54b01fbab3c

test:
  secret_key_base: febee934d266d2fbdd98b899213321200f9f7bf5e9aef44986bf9ae819dd8eb83726b536b74cd047eab6178f4e9323c6b01c2281abe7cba8faf3475b96a2c834

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
